admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

api_events:
    type: rest
    prefix: /api
    resource: AppBundle\Controller\EventController

api_users:
    type: rest
    prefix: /api
    resource: AppBundle\Controller\UserController

api_locations:
    type: rest
    prefix: /api
    resource: AppBundle\Controller\LocationController

rest_registrations:
    type: rest
    prefix: /api
    resource: AppBundle\Controller\RegistrationController