# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.form.registration:
        class: AppBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: app_user_registration }
    app.form.profile:
            class: AppBundle\Form\ProfileFormType
            tags:
                - { name: form.type, alias: app_user_profile }

    admin.speed_dating_event:
          class: AppBundle\Admin\SpeedDatingEventAdmin
          arguments: [~, AppBundle\Entity\SpeedDatingEvent, ~]
          tags:
              - { name: sonata.admin, manager_type: orm, group: Events, label: Speed Dating Events }
    admin.location:
          class: AppBundle\Admin\LocationAdmin
          arguments: [~, AppBundle\Entity\Location, ~]
          tags:
              - { name: sonata.admin, manager_type: orm, group: Events, label: Locations }
    admin.establishment:
          class: AppBundle\Admin\EstablishmentAdmin
          arguments: [~, AppBundle\Entity\Establishment, ~]
          tags:
              - { name: sonata.admin, manager_type: orm, group: Events, label: Establishments }

    admin.user:
          class: AppBundle\Admin\UserAdmin
          arguments: [~, AppBundle\Entity\User, ~]
          tags:
              - { name: sonata.admin, manager_type: orm, group: Users, label: Users }
    admin.user_category:
          class: AppBundle\Admin\UserCategoryAdmin
          arguments: [~, AppBundle\Entity\UserCategory, ~]
          tags:
              - { name: sonata.admin, manager_type: orm, group: Users, label: User categories }