<?php

namespace AppBundle\Entity;
use Doctrine\ORM\EntityRepository;
use Symfony\Component\Validator\Constraints\DateTime;

/**
 * RegistrationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends EntityRepository
{
    /**
     * Find all events that are to come
     * @return array
     */
    public function findNext() {
        $query = $this->createQueryBuilder('p')
            ->where('p.dateStart > :date')
            ->setParameter('date', new \DateTime('now'))
            ->orderBy('p.dateStart', 'ASC')
            ->getQuery();

        return $query->getResult();
    }
}